### ISSUE TITLE
Crashes on "New Game" FFIII 1.2.3

### ISSUE THREAD

**Issue by ratherDashing** [frangarcj/ff3_vita#4]
[psp2core-1629902284-0x00000526cb-eboot.bin.psp2dmp.gz](https://github.com/frangarcj/ff3_vita/files/7047831/psp2core-1629902284-0x00000526cb-eboot.bin.psp2dmp.gz)
Crashes on "New Game" for me.  I tried both repatch and fd_fix.  It creates a save.bin file.  Tried deleting that and starting again, same thing.
FFIII version is 1.2.3

**Comment by frangarcj** [comment]
Try with latest and don't remove the file

**Comment by ratherDashing** [comment]
That solved it.  Thanks!
